### ISSUE TITLE
When trying to login with GoogleID to register at SoCraTes I get an error 500

### ISSUE THREAD

**Issue by adi-bolb** [softwerkskammer/Agora#950] opened 2015-04-28 17:16 UTC
Click on Anmelden -> Google -> Error
Operating System: Ubuntu 14.10
Browser: Firefox
Date, Time: 2015 04 28, 19:15 CEST

Error detail:
Error: Authentication failed.
    at createUserObject (socrates/lib/authentication/index.js:28:23)
    at module.exports (socrates/lib/authentication/index.js:43:3)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:82:5)
    at next (node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:82:5)
    at node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (node_modules/express/lib/router/index.js:321:12)
    at next (node_modules/express/lib/router/index.js:261:10)
    at expressInit (node_modules/express/lib/middleware/init.js:23:5)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (node_modules/express/lib/router/index.js:302:13)
    at node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (node_modules/express/lib/router/index.js:321:12)
    at next (node_modules/express/lib/router/index.js:261:10)
    at query (node_modules/express/lib/middleware/query.js:28:5)

**Comment by leider** [comment] 2015-04-28 17:20
Shit. Can you login with GitHub? We'll fix the mess later

**Comment by leider** [comment] 2015-04-28 17:21
Or try: log into Softwerkskammer first. Then go to Socrates

**Comment by adi-bolb** [comment] 2015-04-28 17:32
Ok, it worked on Softwerkskammer, but the Google session does not seem to pass from one site to the other.
I tried with Git, but it said that I have a timeout for the waitlist. It took me max 5 minutes to fill-in.
Now when I try to register on the waitlist it says "Subscription is currently not allowed.
Subscription is not yet available, or all spots are taken.".

I give up...

**Comment by leider** [comment] 2015-04-28 17:44
We'll come back to you.

**Comment by adi-bolb** [comment] 2015-04-28 18:57
I registered in the end with GitHub. Thanks!

**Comment by JeroenDeDauw** [comment] 2015-05-06 15:41
I encountered what is presumably the same issue and also ended up using GitHub for registration.

![socrates_0](https://cloud.githubusercontent.com/assets/146040/7496813/d4c29b36-f416-11e4-997d-63a649f412b3.png)

Note that the redirect URL here is pointing to the wrong domain.
![socrates_1](https://cloud.githubusercontent.com/assets/146040/7496816/d4c8a440-f416-11e4-8640-5ad06060bcc6.png)

I'm using the Google multi account thing. On this page I picked the first account. No screenshot of the full window as I do not know if it is wise to share the tokens in the URL.
![socrates_2](https://cloud.githubusercontent.com/assets/146040/7496814/d4c65938-f416-11e4-8eb1-b8994aa053cb.png)

![socrates_3](https://cloud.githubusercontent.com/assets/146040/7496815/d4c6f1a4-f416-11e4-8bd8-8f896927c376.png)

**Comment by leider** [comment] 2015-06-14 21:40
Is this still an issue? @JeroenDeDauw @adi-bolb please check once more. :)

**Comment by JeroenDeDauw** [comment] 2015-06-14 23:46
I can still not log in with my main Google account. Same error as in the screenshot posted earlier.

**Comment by leider** [comment] 2015-06-15 06:46
Thank you.

**Comment by georgberky** [comment] 2016-02-08 12:56
I get this problem when I use Stack Exchange to sign into Softwerkskammer. When I manually key in the base URL and try again, it works. Anything I can help to reproduce the problem?

**Comment by leider** [comment] 2016-02-08 13:44
We assume that the initial problem correlates to a combination of OS and Browser / Browser settings.

Stackexchange may be different. Can you open y new bug for that?

**Comment by NicoleRauch** [comment] 2016-04-19 22:03
@adi-bolb @JeroenDeDauw After a very long time of wondering and guessing, we finally managed to fix this issue. It would be great if you could try this out and report back, but I totally understand it if you don't want to do this after such a long time.

**Comment by JeroenDeDauw** [comment] 2016-04-20 11:23
Works as far as I can tell. I tried logging in a week or two ago and then it did not, so yes, this looks like it has been fixed. Thanks

**Comment by NicoleRauch** [comment] 2016-04-20 11:27
Thanks for your feedback @JeroenDeDauw ! I will close this issue.

**Closed by NicoleRauch** 2016-04-20 11:27 UTC
